---
title: "Past Performance *Is* Indicative of Future Results"
author:
  affiliation: Union College Department of Economics Senior Thesis
  name: Gregory Langner
date: "March 2018"
output:
  html_document:
    collapsed: no
    toc: yes
    toc_depth: 4
    toc_float: yes
subtitle: Momentum Strategies in the U.S. Equity Markets
abstract: "I successfully replicate the findings of Asness, Moskowitz, and Pedersen (2013) that momentum strategies in zero cost, long-short neutral portfolios are profitable. I expand on their work in three ways: First, I find that profits are much higher when momentum portfolios are constructed using only top and bottom decile performers rather than top and bottom half performers. Second, I find that 6-month return signals are much less profitable than 12-month return signals. Finally, I find that the returns of momentum portfolios outperform a zero cost portfolio that is long the S&P 500 and short a riskless asset that yields 0.5% per month."
---


```{r message=FALSE, echo=FALSE}
library(tidyverse)
library(lubridate)
library(stargazer) 
```

```{r message=FALSE, echo=FALSE}
#Read the original Quandl data set.
stocks <- read_csv("wiki_prices_key_columns.csv")
```

```{r echo=FALSE}
#Create a month and year variable.
stocks <- arrange(stocks, ticker, date)
stocks$month <- month(stocks$date)
stocks$year <- year(stocks$date)
```


```{r echo=FALSE}
#Examine trading volume statistics to exclude stocks that are smaller or pose problems for liquidity.
stocks$dollar_vol <- (stocks$adj_close)*(stocks$adj_volume)

stocks <- stocks %>% group_by(ticker, month, year) %>% mutate(monthly_vol=sum(dollar_vol))
stocks <- stocks %>% ungroup()
```

```{r echo=FALSE}
#Create a monthly data set from the daily Quandl data set.
stocks <- arrange(stocks, ticker, date)
monthly <- filter(stocks, stocks$month != lead(stocks$month))
```

```{r echo=FALSE}
#Calculate monthly returns.
monthly$return <- (monthly$adj_close - lag(monthly$adj_close))/lag(monthly$adj_close)

monthly$return <- ifelse(monthly$ticker!=lag(monthly$ticker), NA, monthly$return) 

write_csv(monthly, "monthly_thesis_data.csv")
```

```{r message=FALSE, echo=FALSE}
monthly <- read_csv("monthly_thesis_data.csv")
monthly <- arrange(monthly, ticker, date)
monthly <- filter(monthly, monthly$year >= 1971)
monthly <- filter(monthly, date<as.Date("2017-10-01"))
```


```{r echo=FALSE}
#Calculate a rolling 12 month return for each stock.
monthly <- monthly %>% group_by(ticker) %>% mutate(ret12=(adj_close-lag(adj_close, 12))/(lag(adj_close, 12)))
monthly <- filter(monthly, is.na(ret12)==FALSE)
```

```{r echo=FALSE}
#Rank each stock by trading value and filter for a limit of the top 500 stocks by trading value.
monthly <- monthly %>% group_by(month, year) %>% mutate(month_vol_rank=rank(-monthly_vol))
monthly <- filter(monthly, month_vol_rank<=500)
```


```{r echo=FALSE}
#Rank each stock based on 12 month rolling return.
monthly <- monthly %>% group_by(month, year) %>% mutate(rank=rank(ret12))
```


```{r echo=FALSE}
monthly <- monthly %>% group_by(month, year) %>% mutate(dated_avg=mean(rank, na.rm=TRUE))
monthly$weight <- monthly$rank-monthly$dated_avg
```


```{r echo=FALSE}
monthly$pos_weight <- monthly$weight
monthly$pos_weight <- ifelse(monthly$pos_weight < 0, NA, monthly$pos_weight)

monthly <- monthly %>% group_by(month, year) %>% mutate(c=sum(pos_weight, na.rm=TRUE))

monthly$scaled_weight <- (monthly$weight)/(monthly$c)
```


```{r echo=FALSE}
monthly <- monthly %>% group_by(ticker) %>% mutate(weight_times_ret=(1+return)*lag(scaled_weight))

scaled_port <- monthly %>% group_by(year, month) %>% summarize(portfolio_val=sum(weight_times_ret, na.rm=TRUE), no_stocks=n())

scaled_port$cum_gain <- cumsum(scaled_port$portfolio_val)

scaled_port$date <- as.Date(paste0(as.character(scaled_port$month),"/15/",as.character(scaled_port$year)), format="%m/%d/%Y")
```


```{r echo=FALSE, fig.width=6.25}
ggplot(scaled_port, aes(x=date)) + geom_line(aes(y=no_stocks), color="blue3") + labs(title = "Figure 1", subtitle="Number of Stocks Included in Portfolio") + ylab("Stocks") + xlab("Date") + theme_bw()
```


```{r message=FALSE, echo=FALSE}
monthly$monthly_vol_mil <- (monthly$monthly_vol)/1000000
```

```{r message=FALSE, echo=FALSE, results='asis'}
stargazer(data.frame(select(monthly, "monthly_vol_mil", "return", "ret12")), title = "Table I", notes = "Descriptive statistics of the original Wiki EOD Stock Price data set after being transformed into a monthly format.                         ", covariate.labels = c("Monthly Trading Value (Millions USD)", "1-Month Return", "12-Month Return"), type = "html", median = TRUE, column.sep.width = "10pt")
```


```{r message=FALSE, echo=FALSE}
aqr_data <- read_csv("aqr_data.csv")

aqr_data$date <- as.Date(aqr_data$date, "%m/%d/%Y")
aqr_data$month <- month(aqr_data$date)
aqr_data$year <- year(aqr_data$date)
aqr_data <- filter(aqr_data, date<as.Date("2017-10-01"))
```

```{r echo=FALSE}
merged <- full_join(scaled_port, aqr_data, by=c("month", "year"))
merged <- select(merged, date.y, year, month, ret, portfolio_val, no_stocks, cum_gain, cum_ret_0)

merged <- rename(merged, Langner=cum_gain)
merged <- rename(merged, AMP=cum_ret_0)
merged <- rename(merged, date=date.y)
```


```{r echo=FALSE, fig.width=7.1}
#fig.width=10, 
merged_long <- gather(data = merged, value = return, key = Portfolio, Langner, AMP)

ggplot(merged_long, aes(x=date)) + 
  geom_line(aes(y=return, color=Portfolio)) + 
  labs(title="Figure 2") + 
  ylab("Cumulative Return") + xlab("Date") + 
  theme(axis.text.x = element_text(size = 20)) +
  scale_x_date(date_breaks = "6 years", date_labels = "%Y") + 
  labs(subtitle = "Cumulative Returns From Momentum Portfolios") +
  scale_color_manual(labels = c("AMP", "Langner"), values = c("blue", "red")) +
  theme_bw() 
```


```{r message=FALSE, results='asis', echo=FALSE}
stargazer(data.frame(select(merged, "ret", "portfolio_val")), title = "Table II", notes = "Descriptive statistics of momentum portfolio returns from January 1972 through September 2017.", covariate.labels = c("AMP", "Langner"), omit = "year", type = "html", median = TRUE)
```


```{r echo=FALSE, fig.width=6.25}
cor <- monthly %>% group_by(month, year) %>% summarize(correlation=cor(ret12, return))

cor$date <- as.Date(paste0(as.character(cor$month), "/15/", as.character(cor$year)), format = "%m/%d/%Y")

ggplot(cor, aes(x=date)) + 
  geom_line(aes(y=correlation)) + 
  geom_hline(yintercept = 0, size = 0.2, color = "gray40") + 
  geom_smooth(aes(y=correlation), method = lm, color = "red") + 
  labs(title = "Figure 3", subtitle="Correlation Between Monthly Return and Previous 12-Month Return") + 
  ylab("Correlation") + xlab("Date") + theme_bw()
```
 

```{r echo=FALSE, include=FALSE}
langner_reg <- lm(correlation ~ date, data = cor)
summary(langner_reg)

cor$pred <- predict(langner_reg, cor)
#ggplot(cor, aes(y=correlation, x=pred)) + geom_point() + geom_line(aes(y=pred, x=pred), color="red")
```

```{r results='asis', echo=FALSE, include=FALSE}
stargazer(langner_reg, type = "html")
```


```{r message=FALSE, echo=FALSE}
sp500 <- read_csv("sp500 - Sheet1.csv")
sp500$date <- as.Date(sp500$date, "%m/%d/%Y")
sp500 <- arrange(sp500, date)
sp500$month <- month(sp500$date)
sp500$year <- year(sp500$date)
sp500 <- filter(sp500, year > 1971)
sp500 <- filter(sp500, date != as.Date("2017-10-01"))
```

```{r echo=FALSE}
#This is not a zero-cost, long-short neutral strategy, so account for monthly borrowing costs of 50 basis points.
sp500$ret_minus_50bps <- (sp500$return-0.005)

sp500$SP500 <- cumsum(sp500$ret_minus_50bps)
```

```{r echo=FALSE}
sp_merge <- full_join(merged, sp500, by=c("month", "year"))
```

```{r echo=FALSE, fig.width=7.15}
sp_long <- gather(data = sp_merge, value = returns, key = Portfolio, Langner, AMP, SP500)

ggplot(sp_long, aes(x=date.x)) + 
  geom_line(aes(y=returns, color=Portfolio)) + 
  labs(title = "Figure 4", subtitle="Cumulative Returns From Momentum Portfolios Compared to the S&P 500") + 
  ylab("Cumulative Return") + xlab("Date") + 
  scale_x_date(date_breaks = "6 years", date_labels = "%Y") +
  scale_color_manual(labels = c("AMP", "Langner", "S&P 500"), values = c("blue", "red", "hotpink")) + theme_bw()
```


```{r echo=FALSE}
monthly1990 <- select(monthly, ticker, date, month, year, monthly_vol, return, ret12, rank, weight_times_ret)
monthly1990 <- filter(monthly1990, year>=1990)

monthly1990$good <- ifelse(monthly1990$rank>=451, 1, 0)
monthly1990$bad <- ifelse(monthly1990$rank<=50, 1, 0)

monthly1990$include <- ifelse(monthly1990$good==monthly1990$bad, 0, 1)
monthly1990 <- filter(monthly1990, include==1)
```

```{r echo=FALSE}
monthly1990 <- monthly1990 %>% group_by(month, year) %>% mutate(ret_rank=rank(ret12)) 
monthly1990 <- monthly1990 %>% group_by(month, year) %>% mutate(dated_avg=mean(ret_rank, na.rm = TRUE))

monthly1990$weight <- monthly1990$ret_rank-monthly1990$dated_avg

monthly1990$pos_weight <- monthly1990$weight
monthly1990$pos_weight <- ifelse(monthly1990$pos_weight < 0, NA, monthly1990$pos_weight)

monthly1990 <- monthly1990 %>% group_by(month, year) %>% mutate(c=sum(pos_weight, na.rm=TRUE))

monthly1990$scaled_weight <- (monthly1990$weight)/(monthly1990$c)

monthly1990 <- monthly1990 %>% group_by(ticker) %>% mutate(weight_times_ret=(1+return)*lag(scaled_weight))
```

```{r echo=FALSE}
#Construct the first alternative portfolio from the top and bottom decile of 12 month returns.
port_1990<- monthly1990 %>% group_by(year, month) %>% summarize(portfolio_val=sum(weight_times_ret, na.rm=TRUE), no_stocks=n())
port_1990$Langner100 <- cumsum(port_1990$portfolio_val)
port_1990$date <- as.Date(paste0(as.character(port_1990$month),"/15/",as.character(port_1990$year)), format="%m/%d/%Y")
```


```{r warning=FALSE, message=FALSE, echo=FALSE}
#Bring in the saved monthly data and filter it to cover the same time period as the top and bottom decile portfolio.
month90 <- read_csv("monthly_with_new_variables.csv")
month90 <- arrange(month90, ticker, date)
month90 <- filter(month90, month90$year >= 1990)
month90 <- filter(month90, date<as.Date("2017-10-01"))
month90 <- month90 %>% group_by(ticker) %>% mutate(weight_times_ret=(1+return)*lag(scaled_weight))
```


```{r echo=FALSE}
#Construct new portfolios using the original methodology, from 1990-2017.
port90 <- month90 %>% group_by(year, month) %>% summarize(portfolio_val500=sum(weight_times_ret, na.rm=TRUE), no_stocks=n())
port90$Langner500 <- cumsum(port90$portfolio_val500)
port90$date <- as.Date(paste0(as.character(port90$month),"/15/",as.character(port90$year)), format="%m/%d/%Y")

merged90 <- full_join(port90, port_1990, by=c("month", "year"))
```


```{r echo=FALSE}
#Evaluate returns from AMP's portfolio from 1990-2017.
aqr90 <- filter(aqr_data, year>=1990)
aqr90$AMP <- cumsum(aqr90$ret)

merged_3_90 <- full_join(aqr90, merged90, by=c("month", "year"))
```


```{r echo=FALSE, fig.width=8.35}
merged_3_90_long <- gather(data = merged_3_90, value = returns, key = Portfolio, AMP, Langner100, Langner500)

ggplot(merged_3_90_long, aes(x=date.x)) + 
  geom_line(aes(y=returns, color=Portfolio)) + 
  labs(title = "Figure 5", subtitle="Cumulative Returns from Momentum Portfolios: Selective Signal Inclusion") + 
  ylab("Cumulative Return") + xlab("Date") + 
  scale_x_date(date_breaks = "4 years", date_labels = "%Y") +
  scale_color_manual(labels = c("AMP (1990-2017)", "Langner (Top & Bottom Decile)", "Langner (1990-2017)"), values = c("blue", "springgreen4", "red")) + theme_bw()
```


```{r message=FALSE, results='asis', echo=FALSE}
stargazer(data.frame(select(monthly1990, "return", "ret12")), title = "Table III", notes = "Descriptive statistics of individual stock returns that demonstrate the strongest momentum signals from January 1990 through September 2017.",  covariate.labels = c("1-Month Return", "12-Month Return"), type = "html", median = TRUE)
```


```{r message=FALSE, results='asis', echo=FALSE}
stargazer(data.frame(select(merged_3_90, "portfolio_val500", "portfolio_val")), title = "Table IV", notes = "Descriptive statistics of the returns from portfolios constructed with the top and bottom deciles of stocks from January 1990 through September 2017 compared to original method of portfolio construction.", covariate.labels = c("AMP Methodology", "Top and Bottom Deciles"), type = "html", median = TRUE)
```


```{r echo=FALSE}
cor_1990 <- monthly1990 %>% group_by(month, year) %>% summarize(Langner100=cor(ret12, return))
cor_1990$date <- as.Date(paste0(as.character(cor_1990$month), "/15/", as.character(cor_1990$year)), format = "%m/%d/%Y")
```

```{r echo=FALSE}
#Create a data set to view the correlation of the new data set compared to the original data.
monthly_compare <- filter(monthly, year>1989)
#cor(monthly_compare$return, monthly_compare$ret12)
cor_compare <- monthly_compare %>% group_by(month, year) %>% summarize(Langner500=cor(ret12, return))
cor_compare$date <- as.Date(paste0(as.character(cor_compare$month), "/15/", as.character(cor_compare$year)), format = "%m/%d/%Y")

merged_cor <- full_join(cor_compare, cor_1990, by="date")
```

```{r echo=FALSE, include=FALSE}
mean(merged_cor$Langner100)
mean(merged_cor$Langner500)
```

```{r echo=FALSE, fig.width=8.5}
merged_cor_long <- gather(data = merged_cor, value = correlations, key = Portfolio, Langner100, Langner500)

ggplot(merged_cor_long, aes(x=date)) + 
  geom_line(aes(y=correlations, color = Portfolio)) + 
  geom_smooth(aes(y=correlations, group=Portfolio, color=Portfolio), method = lm) + 
  labs(title = "Figure 6", subtitle="Correlation Comparison of Momentum Strategies, 1990-2017") + 
  geom_hline(yintercept = 0, size = 0.2, color = "gray40") +
  ylab("Correlation") + xlab("Date") +
  scale_color_manual(labels = c("Langner (Top & Bottom Decile)", "Langner (1990-2017)"), values = c("springgreen4", "black")) + theme_bw()
```


```{r message=FALSE, echo=FALSE}
monthly6 <- read_csv("monthly_thesis_data.csv")
monthly6 <- arrange(monthly6, ticker, date)

monthly6 <- filter(monthly6, date>=as.Date("1971-07-01"))
monthly6 <- filter(monthly6, date<as.Date("2017-10-01"))

monthly6 <- monthly6 %>% group_by(ticker) %>% mutate(ret6=(adj_close-lag(adj_close, 6))/(lag(adj_close, 6)))
monthly6 <- filter(monthly6, is.na(ret6)==FALSE)
```

```{r echo=FALSE}
#Rank each stock by trading value and filtering for a limit of the top 500 stocks by trading value.
monthly6 <- monthly6 %>% group_by(month, year) %>% mutate(month_vol_rank=rank(-monthly_vol))

monthly6 <- filter(monthly6, month_vol_rank<=500)
```

```{r echo=FALSE}
#Rank each stock based on 6 month rolling return.
monthly6 <- monthly6 %>% group_by(month, year) %>% mutate(rank=rank(ret6))

monthly6 <- monthly6 %>% group_by(month, year) %>% mutate(dated_avg=mean(rank, na.rm=TRUE))
monthly6$weight <- monthly6$rank-monthly6$dated_avg

monthly6$pos_weight <- monthly6$weight
monthly6$pos_weight <- ifelse(monthly6$pos_weight < 0, NA, monthly6$pos_weight)

monthly6 <- monthly6 %>% group_by(month, year) %>% mutate(c=sum(pos_weight, na.rm=TRUE))

monthly6$scaled_weight <- (monthly6$weight)/(monthly6$c)
```

```{r echo=FALSE} 
monthly6 <- monthly6 %>% group_by(ticker) %>% mutate(weight_times_ret=(1+return)*lag(scaled_weight))

port6 <- monthly6 %>% group_by(year, month) %>% summarize(portfolio_val=sum(weight_times_ret, na.rm=TRUE), no_stocks=n())
port6$Langner6 <- cumsum(port6$portfolio_val)
port6$date <- as.Date(paste0(as.character(port6$month),"/15/",as.character(port6$year)), format="%m/%d/%Y")
```

```{r echo=FALSE}
merged_612 <- full_join(port6, scaled_port, by=c("month", "year"))
merged_612 <- rename(merged_612, portfolio_val6=portfolio_val.x)
merged_orig_6 <- full_join(merged, port6, by=c("month", "year"))
merged_orig_6 <- rename(merged_orig_6, "Langner12"="Langner")
```

```{r echo=FALSE, fig.width=8.1}
merged_orig_6_long <- gather(data = merged_orig_6, value = returns, key = Portfolio, AMP, Langner6, Langner12)

ggplot(merged_orig_6_long, aes(x=date.x)) + 
  geom_line(aes(y=returns, color=Portfolio)) + 
  labs(title = "Figure 7", subtitle="Cumulative Returns from Momentum Portfolios: 6-Month vs 12-Month Signals") + 
  ylab("Cumulative Return") + xlab("Date") + 
  scale_x_date(date_breaks = "6 years", date_labels = "%Y") +
  scale_color_manual(labels = c("AMP", "Langner (12-Month Signal)", "Langner (6-Month Signal)"), values = c("blue", "red", "purple")) + theme_bw()
```


```{r message=FALSE, results='asis', echo=FALSE}
stargazer(data.frame(select(monthly6, "return", "ret6")), title = "Table V", notes = "Descriptive statistics of individual stock returns over the course of 1 month and 6 months.", covariate.labels = c("1-Month Return", "6-Month Return"), type = "html", median = TRUE)
```


```{r message=FALSE, results='asis', echo=FALSE}
stargazer(data.frame(select(merged_612, "portfolio_val.y", "portfolio_val6")), title = "Table VI", notes = "Descriptive statistics of the returns from portfolios constructed with 12-month momentum signals and portfolios constructed with 6-month momentum signals.", covariate.labels = c("12-Month Signals", "6-Month Signals"), omit = "year", type = "html", median = TRUE )
```


```{r echo=FALSE}
cor_6 <- monthly6 %>% group_by(month, year) %>% summarize(Langner6=cor(ret6, return))
cor_6$date <- as.Date(paste0(as.character(cor_6$month), "/15/", as.character(cor_6$year)), format = "%m/%d/%Y")
cor_6_merge <- full_join(cor_6, cor, by="date")
cor_6_merge <- rename(cor_6_merge, "Langner12"="correlation")
```

```{r echo=FALSE, include=FALSE}
mean(cor_6$Langner6)
mean(cor_1990$Langner100)
mean(cor$correlation)
```

```{r echo=FALSE, fig.width=8.2}
cor_6_merge_long <- gather(data = cor_6_merge, value = correlations, key = Portfolio, Langner6, Langner12)

ggplot(cor_6_merge_long, aes(x=date)) + 
  geom_line(aes(y=correlations, color = Portfolio)) + 
  geom_hline(yintercept = 0, size = 0.2, color = "gray40") + 
  geom_smooth(aes(y=correlations, group=Portfolio, color=Portfolio), method = lm) +
  labs(title = "Figure 8", subtitle="Correlation Comparison of Momentum Strategies: 6-Month vs 12-Month Signals") + 
  ylab("Correlation") + xlab("Date") +
  scale_color_manual(labels = c("Langner (12-Month Signal)", "Langner (6-Month Signal)"), values = c("black", "purple")) + theme_bw()
```



